[package]
name = "sfml-bunnymark"
version = "0.1.0"
authors = ["Adil Basar <descrout@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.15.1"
rand = "0.7.3"